### ISSUE TITLE
Let alias plugin accept and replace arguments

### ISSUE THREAD

**Issue by fortysix2ahead** [kergoth/beets-kergoth#2]
I already implemented this behaviour, but maybe you are intested and accept a PR. Instead of appending the provided beets arguments to the alias, do a replacement first. So you can do something like this:

```yaml
alias:
  aliases:
    live-albums: ls -a albumartist:{0} album:{1}
```

With having such an alias definition you can then do this:
```bash
beet live-albums yello live
```

and beets will be called with
```bash
beet ls -a albumartist:yello album:live
```
